---
title: "shrub data cleaning"
author: "Carmen"
date: "November 9, 2017"
output: 
    html_document:
        toc: TRUE
---


```{r, include = F}
library(dplyr)
library(readxl)
library(ggplot2)
```

# Load data
```{r}
dfshrub <- read_excel("~/../Dropbox (Stephens Lab)/Shrub_experiment/Data/Compiled/ShrubCov_compiled_20171108.xlsx")
```

# Rename columns
```{r}
dfshrub <- dfshrub %>% 
  rename(cov_cm = `cover (cm)`) %>% 
  rename(ht_cm = `ht (cm)`)
```

# Make everything uppercase
```{r}
dfshrub <- dfshrub %>% 
  mutate(island = toupper(island))
```


# Take out gaps for now
```{r}
dfshrub <- dfshrub %>% 
  filter(spp != "gap" & spp != "Gap")
summary(as.factor(dfshrub$spp))
summary(as.numeric(dfshrub$ht_cm))
dfshrub$ht_cm <- as.numeric(dfshrub$ht_cm)
dfshrub %>% 
  arrange(Compartment, island, plot, transect)
```

# Calculate shrub cov, ht, shrubarea for each plot

## Weighted mean shrub height
```{r}
ht <- dfshrub %>%
  dplyr::select(Compartment, island, plot, spp, cov_cm, ht_cm) %>% 
  group_by(Compartment, island, plot) %>% 
  mutate(ht_wm.cm = weighted.mean(ht_cm, cov_cm)) %>% 
  ungroup() %>% 
  dplyr::select(Compartment, island, plot, ht_wm.cm) %>% 
  distinct() 
ht
```

```{r}
dfshrub <- dfshrub %>% 
  group_by(Compartment, island, plot) %>% 
  summarize(Cov1.3 = sum(cov_cm))
dfshrub <- full_join(dfshrub, ht)
dfshrub <- dfshrub %>% 
  rename(Ht1.3 = ht_wm.cm) %>% 
  mutate(shrubarea = Cov1.3*Ht1.3)
dfshrub
```


# Take a look
```{r}
hist(dfshrub$shrubarea)
dfshrub %>% 
  group_by(Compartment, island) %>% 
  summarise(n())
```

# Rename to match seedling columns
```{r}
dfshrub <- dfshrub %>% 
  rename(compartment = Compartment)
```

# Save
```{r}
save(dfshrub, file = "../../../compiled_data/dfshrubs.Rdata")
```


