---
title: "plot_coef_final"
author: "Carmen"
date: "4/1/2020"
output: html_document
---

```{r, include = F}
require(tidyverse)
require(gridExtra)
require(egg)
require(grid)
```


# Load summarized results
```{r}
filename <- paste("../../../../results/data/summary_emerge_coef_", data_date,"_", n_reps, ".Rdata", sep = "")

load(file = filename)
```


## Plot 
```{r}
plot_emerge_prop <- 
  ggplot(summary_emerge )+
  theme_bw()+
  geom_line(aes(x = Years, y = mean, col = simspp, group = simspp, linetype = Species), size = 1.1)+
  geom_ribbon(aes(x = Years, ymin = mean-sd, ymax = mean+sd, fill = simspp, group = simspp), alpha = .2)+
  ylab("Proportion of initial trees emerged")+
  xlab("Years since fire")+
  #ggtitle(paste("Results for", max(dfsimallreps$rep), "simulations", sep = " "))+
  theme(legend.position = c(0.35, 0.4))+
   scale_fill_manual(name = "Shrub species", 
                    values = c("#888888", "#d95f02", "#1b9e77", "#e7298a"), 
                                labels = c("All shrub species", "Manzanita", 
                                "Whitethorn", 
                                "Deerbrush"))+

  scale_color_manual(name = "Shrub species", 
                    values = c("#888888", "#d95f02","#1b9e77",  "#e7298a"), 
                                labels = c("All shrub species", "Manzanita", 
                                "Whitethorn", 
                                "Deerbrush"))+
  scale_linetype_discrete(labels = c("White fir",
                          "Ponderosa pine"))+
  
  theme(text = element_text(size = 13), 
        
        legend.title = element_blank(),
        legend.spacing=unit(0, "cm"),
        legend.text=element_text(size=12),
        axis.text=element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        strip.background = element_blank(),strip.text.x = element_blank(),
        axis.text.x = element_blank(),
        plot.margin = margin(0,0,0,0, "cm")
        )+
  xlab(element_blank())+
  xlim(9,max(summary_emerge$Years))+
  ylim(c(0,1))+
  facet_wrap(~Species, nrow = 1)

plot_emerge_prop
```

# Plot Q50 
```{r}
Q50 <- summary_emerge %>% 
  mutate(dist50 = mean-.5) %>% 
  filter(dist50>0) %>%
  ungroup() %>% 
  group_by(Species, simspp) %>% 
  filter(dist50 == min(dist50)) %>% 
  mutate(bound = "mean")

Q50_ub <- summary_emerge %>% 
  mutate(lowerdist50 = mean-sd-.5) %>% 
  filter(lowerdist50>0) %>%
  ungroup() %>% 
  group_by(Species, simspp) %>% 
  filter(lowerdist50 == min(lowerdist50)) %>% 
  mutate(bound = "upper")

Q50_lb <- summary_emerge %>% 
  mutate(upperdist50 = mean+sd-.5) %>% 
  filter(upperdist50>0) %>%
  ungroup() %>% 
  group_by(Species, simspp) %>% 
  filter(upperdist50 == min(upperdist50)) %>% 
  mutate(bound = "lower")

```

```{r}
Q50 <- full_join(Q50, Q50_lb) 
Q50 <- full_join(Q50, Q50_ub) 

Q50 <- Q50 %>% 
  dplyr::select(Years, Species, simspp, bound)
```

## pivot wider
```{r}
Q50 <- pivot_wider(Q50, names_from = bound, values_from = Years) %>% 
  dplyr::select(Species, simspp, lower, mean, upper)
```

```{r}
Q50 <- Q50 %>% 
  mutate(shrub = case_when(
    Species == "PIPO" ~ simspp,
    TRUE ~ "CECO"
  ))
```


```{r}
Q50plot <- ggplot(Q50, aes(col = simspp))+
  theme_bw()+
  geom_errorbarh(aes(y = shrub, xmin = lower, xmax = upper), size = 1, height = .6)+
  geom_point(aes(x = mean, y = shrub), size = 1, fill = "white", stroke = 1.5)+
  #scale_shape_manual(values = c(16,21))+
  scale_color_manual(values = c("#888888", "#d95f02","#1b9e77",  "#e7298a"))+
  theme(axis.text.y = element_blank(),
        legend.position = "none", 
        text = element_text(size = 13),
        axis.text = element_text(size = 12),
        panel.grid.major.y  = element_blank(),
         strip.background = element_blank(),
        strip.text.x = element_blank(),
        plot.margin = margin(0,0,0,0, "cm"),
        axis.ticks.y = element_blank())+
  xlim(c(9,max(summary_emerge$Years)))+
  xlab("Years since fire")+
  ylab("Shrub\nspecies")+
  facet_wrap(~Species, nrow = 1)
Q50plot
```

# Save
```{r}
filename <- paste("../../../../results/figures/Simulations/shrub_species_coef_withQ50_facet_", data_date,"_", n_reps, ".jpeg", sep = "")

g <- ggarrange(plot_emerge_prop, Q50plot, heights = c(2.5,0.5), widths = 4)
ggsave(filename, g, width = 8, height = 4.2)
```

