---
title: "plot_base_final"
author: "Carmen"
date: "4/1/2020"
output: 
  html_document:
    toc: TRUE
---


```{r}
setwd("~/../Shrubs-Seedlings/code/Simulations/")
```

```{r, include = F}
require(tidyverse)
require(gridExtra)
```

# If you're running this code on its own, you have to define data_date and n_reps at the top

# Load summary
```{r}
filename <- paste("../../../../results/data/summary_emerge_density_base_", data_date,"_", n_reps, ".Rdata", sep = "")
load(file = filename)
```

```{r}
filename <- paste("../../../../results/data/summary_emerge_prop_base_", data_date,"_", n_reps, ".Rdata", sep = "")
load(file = filename)
```

## Plot 
```{r}
ggplot(summary_emerge_prop)+
  theme_bw()+
  geom_line(aes(x = Years, y = mean, col = Species, group = Species, linetype = Species), size = 1)+
  geom_ribbon(aes(x = Years, ymin = mean-sd, ymax = mean+sd, fill = Species, group = Species), alpha = .3)+
  ylab("Proportion of initial trees that have emerged")+
  xlab("Years since fire")+
  theme(legend.position = c(0.75, 0.3))+
   scale_fill_manual(values = c( "#899DA4", "#9A8822"), 
                                labels = c("White fir", "Ponderosa pine"))+

  scale_color_manual(values = c("#899DA4", "#9A8822"), 
                                   labels = c("White fir", "Ponderosa pine"))+

  scale_linetype_discrete(     labels = c("White fir", "Ponderosa pine"))+

  
  theme(text = element_text(size = 11), 
        
        legend.title = element_blank(),
        legend.spacing=unit(0, "cm"),
        legend.text=element_text(size=10),
        legend.margin = margin(0, 0, 0, 0)
        )+
  xlab(element_blank())+
  xlim(8,max(summary_emerge_prop$Years))+
  ylim(c(-0.05,1))
filename <- paste("../../../../results/figures/Simulations/base_prop_line_", data_date, "_", n_reps,".png", sep = "")
ggsave(file = filename, width = 5, height =4, dpi = 400)
```


```{r}
ggplot(summary_emerge_density)+
  theme_bw()+
  geom_line(aes(x = Years, y = mean, col = Species, group = Species, linetype = Species), size = 1)+
  geom_ribbon(aes(x = Years, ymin = mean-sd, ymax = mean+sd, fill = Species, group = Species), alpha = .3)+
  
  xlab("Years since fire")+
  theme(legend.position = c(0.75, 0.3))+
    ylab("Density of emerged trees per ha")+
  scale_fill_manual(values = c( "#899DA4", "#9A8822"), 
                                labels = c("White fir", "Ponderosa pine"))+

  scale_color_manual(values = c("#899DA4", "#9A8822"), 
                                   labels = c("White fir", "Ponderosa pine"))+

  scale_linetype_discrete(     labels = c("White fir", "Ponderosa pine"))+

  
  theme(text = element_text(size = 11), 
        
        legend.position = "none"
        )

filename <- paste("../../../../results/figures/Simulations/base_density_line_", data_date,"_", n_reps, ".png", sep = "")
ggsave(file = filename, width = 5, height =4, dpi = 400)
```


# Are ending proportions significantly different between pine and fir?
```{r}
ggplot(summary_emerge_prop)+
  geom_histogram(aes(x = mean, fill = Species), bins =20)+
  theme_minimal()
```

# Find mean prop emerged at end of sim for each species (for Results Section)
```{r}
summary_emerge_prop %>% 
  group_by(Species) %>% 
  filter(mean == max(mean))
```

# Finding ending maximum density
```{r}
summary_emerge_density %>% 
  group_by(Species) %>% 
  filter(mean == max(mean))
```
