---
title: "render all simulation plots"
author: "Carmen"
date: "January 15, 2020"
output: 
  html_document:
    toc: TRUE
---

```{r setup}
library(knitr)
```

```{r defining}
data_date <<- "2020-12-15"
n_reps <<- "200"
```

```{r summarizing, warning = F}
strt_all <- Sys.time()
setwd("~/../Shrubs-Seedlings/code/Simulations/plotting/summarize/")
rmarkdown::render("simulations_plot_base.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_base_plot_extra.Rmd", "html_document", quiet = T) # this takes a while 
rmarkdown::render("simulations_plot_ShrubSpecies.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies_coef.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies_GROWTH.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies_INDEX.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_summarize_gradient.Rmd", "html_document", quiet = T)
print(Sys.time()-strt_all)
```

```{r plotting, warning = F}
setwd("~/../Shrubs-Seedlings/code/Simulations/plotting/final_pretty/")
rmarkdown::render("plot_base_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_ShrubSpecies_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_coef_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_growth_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_index_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_Gradient_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_growth_climate_supp.Rmd", "html_document", quiet = T)
```

