---
title: "Growth_mort"
author: "Carmen"
date: "October 31, 2019"
output: 
  html_document:
    TOC: TRUE
---

```{r, include = F}
setwd("~/Shrubs-Seedlings/code/Simulations/")
require(raster)
require(tidyverse)
require(tmap)
require(sf)
require(sp)
require(tmaptools)
require(knitr)
```

# Load functions

## Normalize function
```{r}
source("functions/normalize.R")
```

## Initialization function
```{r}
source("functions/initialize.R")
```

## Growth functions
```{r}
source("functions/abcogrowth.R")
source("functions/pipogrowth.R")
```

## Mortality functions
```{r}
source("functions/abcomort.R")
source("functions/pipomort.R")
```


## Simulation function
```{r}
source("functions/sim.R")
```

## Iteration function
```{r}
source("functions/iterate.R")
```

# Initialize
```{r}
initialize()
```

# Simulate across 20 years
```{r}
suppressMessages(sim(20))
summary(pts.sf.pipo)
```

# Plot patch
```{r}
tm_shape(p)+
  tm_borders(col = "black", lwd= 5)+
tm_shape(r)+
  tm_raster(alpha = .5, title = "Shrub competition")+
  tm_layout(asp=1:1, legend.outside = T)+
tm_shape(pts.sf.pipo)+
  tm_symbols(size = "Ht_cm_nonnorm", col = "darkgreen", size.max = 3000)+
tm_shape(pts.sf.abco)+
  tm_symbols(size = "Ht_cm_nonnorm", col = "darkblue", size.max = 3000)
```

# Iterate 
```{r}
iterate(100)
dfsimallreps %>% 
  group_by(rep) %>% 
  summarize(mean(Ht_cm_nonnorm))
```

# Summarize

## Height by shrub competition
```{r}
dfsimallreps <- dfsimallreps %>% 
  ungroup() %>% 
  mutate(rep = as.factor(paste(rep))) %>% 
  group_by(rep, shrubarea3, Species) %>% 
  mutate(mean_ht_shrubs = mean(Ht_cm_nonnorm))
dfsimallreps %>% select(rep, shrubarea3, mean_ht_shrubs) %>% summary()
```

```{r}
ggplot(dfsimallreps)+
  geom_smooth(aes(x = shrubarea3, y = mean_ht_shrubs, group = Species, col = Species))+
  geom_point(aes(x = shrubarea3, y = mean_ht_shrubs, group = Species, col = Species))+
  theme_bw()
```

## Height by year
```{r}
dfsimallreps <- dfsimallreps %>% 
  ungroup() %>% 
  mutate(rep = as.factor(paste(rep))) %>% 
  group_by(rep, Years, Species) %>% 
  mutate(mean_ht_years = mean(Ht_cm_nonnorm))
dfsimallreps %>% select(rep, Years, mean_ht_years) %>% summary()
```

```{r}
ggplot(dfsimallreps, aes(x = as.factor(Years_nonnorm), y = mean_ht_years, fill = Species, col = Species))+
  geom_boxplot(alpha = .2, outlier.alpha = .02)+
  geom_smooth(aes(x = as.factor(Years_nonnorm), y = mean_ht_years, group = Species, col = Species), size = 1)+
  ggtitle("Results for 300 simulations")+
  xlab("Years since fire")+
  ylab("Average tree ht (cm) by simulation")+
  theme_bw()
```

## Counts by year
```{r}
dfsimallreps <- dfsimallreps %>% 
  ungroup() %>% 
  group_by(rep, Years, Species) %>% 
  mutate(count = n()) %>% 
  mutate(count = as.numeric(count))
```

```{r}
ggplot(dfsimallreps, aes(x = as.factor(Years_nonnorm), y = count, fill = Species, col = Species))+
  geom_boxplot(alpha = .2, outlier.alpha = .02)+
  geom_smooth(aes(x = as.factor(Years_nonnorm), y = count, fill = Species, col = Species), size = 1)+
  ggtitle("Results for 100 simulations")+
  xlab("Years since fire")+
  ylab("Tree count")+
  theme_bw()
```

