---
title: "plot final index"
author: "Carmen"
date: "4/1/2020"
output: html_document
---


```{r, include = F}
require(tidyverse)
require(gridExtra)
require(egg)
require(grid)
```


# Load summary
```{r}
load(file = "../../results/data/summary_emerge_index.Rdata")
```

## Plot 
```{r}
plot_emerge_prop <- 
  ggplot(summary_emerge)+
  geom_line(aes(x = Years, y = mean, linetype = Species,  col = simspp, group = interaction(Species, simspp)), size = 1.1)+
  geom_ribbon(aes(x = Years, ymin = mean-sd, ymax = mean+sd, fill = simspp, group = interaction(Species, simspp)), alpha = .2)+
  ylab("Proportion of initial trees that have emerged")+
  scale_fill_manual(values = c("#d95f02", "#1b9e77", "#e7298a"))+
  xlab(element_blank())+
  scale_color_manual(values = c("#d95f02","#1b9e77", "#e7298a"))+
  theme_bw()+
  theme(text = element_text(size = 11), 
        legend.position = "none",
        panel.grid.minor.y = element_blank())+
  ylim(c(-.05,1))
plot_emerge_prop
```

# Plot Q50 

## Calculate Q50
```{r}
Q50 <- summary_emerge %>% 
  mutate(dist50 = mean-.5) %>% 
  filter(dist50>0) %>%
  ungroup() %>% 
  group_by(Species, simspp) %>% 
  filter(dist50 == min(dist50)) %>% 
  mutate(bound = "mean")

Q50_ub <- summary_emerge %>% 
  mutate(lowerdist50 = mean-sd-.5) %>% 
  filter(lowerdist50>0) %>%
  ungroup() %>% 
  group_by(Species, simspp) %>% 
  filter(lowerdist50 == min(lowerdist50)) %>% 
  mutate(bound = "upper")

Q50_lb <- summary_emerge %>% 
  mutate(upperdist50 = mean+sd-.5) %>% 
  filter(upperdist50>0) %>%
  ungroup() %>% 
  group_by(Species, simspp) %>% 
  filter(upperdist50 == min(upperdist50)) %>% 
  mutate(bound = "lower")

```

```{r}
Q50 <- full_join(Q50, Q50_lb) 
Q50 <- full_join(Q50, Q50_ub) 

Q50 <- Q50 %>% 
  dplyr::select(Years, Species, simspp, bound)
```

## pivot wider
```{r}
Q50 <- pivot_wider(Q50, names_from = bound, values_from = Years) %>% 
  dplyr::select(Species, simspp, lower, mean, upper)
```


```{r}
lower_cein_abco <- Q50[Q50$Species == "ABCO" & Q50$simspp == "CEIN", "lower"] %>% unlist()
mean_cein_abco <- Q50[Q50$Species == "ABCO" & Q50$simspp == "CEIN", "mean"] %>% unlist()
```

## Plot
```{r}
Q50plot <- ggplot()+
 
  theme_bw()+
  geom_errorbarh(data = Q50, aes(col = simspp, y = interaction(Species, simspp), xmin = lower, xmax = upper), size = 1)+
  
   geom_errorbarh(data = Q50 %>% filter(!(Species == "ABCO" & simspp == "CEIN")), aes(y = interaction(Species, simspp), col = simspp, xmin = lower, xmax = upper), size = 1)+
  
  geom_errorbarh(data = Q50 %>% filter((simspp == "CEIN")), aes(col = simspp, y = interaction(Species, simspp), xmin = lower, xmax = max(summary_emerge$Years)), size = 1, height = 0, linetype = "dotted")+
  
  geom_line(aes(y = 5, x = c(lower_cein_abco, mean_cein_abco)), size = 1, col = "#e7298a")+
  
  geom_point(data = Q50, aes(x = mean, y = interaction(Species, simspp), shape = Species, col = simspp), size = 2, fill = "white", stroke = 1.5)+
  scale_shape_manual(values = c(16,21))+

  geom_linerange(data = Q50 %>% filter((Species == "ABCO" & simspp == "CEIN")), aes(x = lower, ymin = 4.6, ymax= 5.45), size = 1, col = "#e7298a")+
  geom_linerange(data = Q50 %>% filter((Species == "PIPO" & simspp == "CEIN")), aes(x = lower, ymin = 5.6, ymax= 6.45), size = 1, col = "#e7298a")+
  
  ylab("Shrub and tree\nspecies combination")+
  scale_color_manual(values = c("#d95f02","#1b9e77",  "#e7298a"))+
  theme(axis.text.y = element_blank(),
        legend.position = "none", 
        text = element_text(size = 11),
        panel.grid.major.y  = element_blank(),
        axis.ticks.y = element_blank())+
  xlim(c(9,max(summary_emerge$Years)))+
  xlab("Years since fire")
Q50plot
```


# Save
```{r}
filename <- paste("../../results/figures/Simulations/shrub_species_index_withQ50", Sys.Date(), ".jpeg", sep = "")

g <- ggarrange(plot_emerge_prop, Q50plot, heights = c(3,1), widths = 2)
ggsave(filename, g, width = 4, height = 5)
```

