---
title: "render_all_shrub_growth_time"
author: "Carmen"
date: "January 15, 2020"
output: 
  html_document:
    toc: TRUE
---

```{r setup}
library(knitr)
setwd("~/Shrubs-Seedlings/code/Simulations/")
```

```{r rendering, warning = F}
strt <- Sys.time()
rmarkdown::render("simulations_plot_base.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies_coef.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies_GROWTH.Rmd", "html_document", quiet = T)
rmarkdown::render("simulations_plot_ShrubSpecies_INDEX.Rmd", "html_document", quiet = T)
print(strt-Sys.time())
```

```{r}
rmarkdown::render("simulations_base_plot_extra.Rmd", "html_document", quiet = T) # this takes a while 
rmarkdown::render("plot_base_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_coef_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_growth_final.Rmd", "html_document", quiet = T)
rmarkdown::render("plot_index_final.Rmd", "html_document", quiet = T)
```

