---
title: "Growth_mort"
author: "Carmen"
date: "October 31, 2019"
output: 
  html_document:
    toc: TRUE
---

# This script runs simulations with the most up-to-date functions

```{r, include = F}
setwd("~/Shrubs-Seedlings/code/Simulations/")
pkgs <- c("raster", "tidyverse", "tmap", "sf", "sp", "tmaptools", "knitr", "mgcv", "gridExtra", "doParallel")
lapply(pkgs, require, character.only = T)
strt <- Sys.time()
```

#### Iteration function
```{r}
print(Sys.time())
source("functions/iterate.R")
```

# Define iterations
```{r}
iterations <- 100
```

# Define length of simulation
```{r}
years_max <<- 50
```

# Iterate 
```{r, warning=FALSE}
time <- Sys.time()
iterate(iterations)
print(paste("That took", round(Sys.time()-time, 1), "minutes"))
```

# Filter out years in which nothing happens
```{r}
max_year <- dfsimallreps %>% 
  group_by(Years, emerged) %>% 
  summarize(sum_emerged = sum(emerged)) %>% 
  filter(emerged ==0) %>% 
  ungroup() %>% 
  summarize(max_year = max(Years)) %>% 
  unlist()
```

```{r}
dfsimallreps <- dfsimallreps %>% 
  filter(Years < max_year+2)
```

# Save results
```{r}
save(dfsimallreps, file = paste("~/Simulations",  Sys.Date(), "_", iterations, ".Rdata", sep = ""))
```


```{r}
print(paste("The whole thing took", round(Sys.time()-strt, 1), "minutes"))
```

