---
title: "Growth_mort"
author: "Carmen"
date: "October 31, 2019"
output: 
  html_document:
    toc: TRUE
---

# This script runs simulations without being spatially explicit. Thus, the functions `shrubclump` and `ratify_r` were removed.

```{r, include = F}
setwd("~/Shrubs-Seedlings/code/Simulations/") # change this if needed

pkgs <- c("tidyverse", "sf", "knitr", "mgcv", "gridExtra", "doParallel")
lapply(pkgs, require, character.only = T)
strt <- Sys.time()
```

#### Iteration function
```{r}
print(Sys.time())
source("functions/iterate.R")
```

# Define stuff

## Define iterations
```{r}
iterations <- 100
```

## Define length of simulation
```{r}
years_max <- 50
```

## Define fire
```{r}
fire <- "AMRC"
```

## Sensitivity methods
```{r}
climate_method <- "historic" #historic, random, uniform_2015, uniform_2016, uniform_2017
conifer_species_method <- "empirical" #random, empirical
shrub_method <- "welch" #emprical, welch, CECO, ARPA, CHSE, LIDE, OTHER
shrub_coefficient <- "empirical"  #emprical, CECO, ARPA, CHSE, LIDE, Other
shrub_heightgrowth <- "CECO"  #emprical, CECO, ARPA, CHSE
n_seedlings <- 200
```

# Iterate 
```{r, warning=FALSE}
time <- Sys.time()
dfsimallreps <- iterate(iterations, fire, years_max, climate_method, conifer_species_method, shrub_method, n_seedlings, shrub_coefficient, shrub_heightgrowth)
print(paste("That took"))
Sys.time()-time
```

# Save results
```{r}
filename <-  paste("~/Simulations",  Sys.Date(), "_", iterations, fire, "_",climate_method,"_", conifer_species_method, "_", shrub_method, ".Rdata", sep = "")
save(dfsimallreps, file =filename)
```

```{r, echo = F}
if(nrow(dfsimallreps)==iterations){
  print("ALERT! Something went wrong.")
}
```

# Filter out years in which nothing happens
```{r}
max_year <- dfsimallreps %>% 
  group_by(Years, emerged) %>% 
  summarize(sum_emerged = sum(emerged)) %>% 
  filter(emerged ==0) %>% 
  ungroup() %>% 
  summarize(max_year = max(Years)) %>% 
  unlist()
```

```{r}
dfsimallreps <- dfsimallreps %>% 
  filter(Years < max_year+2)
```

```{r}
print(paste("The whole thing took"))
round(Sys.time()-strt)
Sys.time()
```
 
# Save results
```{r}
filename <-  paste("~/Simulations",  Sys.Date(), "_", iterations, fire, "_",climate_method,"_", conifer_species_method, "_", shrub_method, "_", shrub_coefficient, "coef.Rdata", sep = "")
save(dfsimallreps, file =filename)
```

