---
title: "tests"
author: "Carmen"
date: "2/19/2020"
output: html_document
---


```{r}
load("~/Simulations2020-02-28_1000AMRC.Rdata")
strt <- Sys.time()
```

```{r, include = F}
require(tidyverse)
require(gridExtra)
```

# Check for reps that got dropped as errors -- should be TRUE
```{r}
length(unique(dfsimallreps$rep)) == max(dfsimallreps$rep)
length(unique(dfsimallreps$rep))
max(dfsimallreps$rep)
```

# Check random independence
```{r}
test <-dfsimallreps %>% tbl_df() %>% group_by(rep, Sdlg) %>% count() %>% group_by(Sdlg) %>% count() %>% filter(n<5)
test
nrow(test)==0
remove(test)
```

# Check for NA and inf values
```{r}
dfsimallreps_summary <- dfsimallreps %>% 
  ungroup() %>%
  mutate(rep = as.factor(paste(rep))) %>% 
  group_by(rep, Years, Species) %>% 
  summarize(mean_ht_years = mean(Ht_cm1))
```

```{r}
summary(dfsimallreps_summary$mean_ht_years)
reps_with_na <- dfsimallreps_summary %>% 
  filter(is.na(mean_ht_years))
dfsimallreps %>% 
  filter(rep %in% reps_with_na$rep) %>% 
  select(Ht_cm1) %>% 
  summary()
```

```{r}
dfsimallreps %>% filter(rep ==309 & Sdlg == 36) %>% 
  ggplot(aes(x = Years, y = Ht_cm1))+
  geom_line()+
  ylim(c(0,4000))
```

```{r}
ggplot(dfsimallreps_summary %>% filter(rep %in% reps_with_na$rep))+
  geom_line(aes(x = Years, y = mean_ht_years, group = interaction(rep, Species), color = interaction(rep, Species)))+
  theme_minimal()+
  ylim(0,2000)
```


# Check different values of error terms

## Diameter

### Abco
```{r}
test <- dfsimallreps %>% 
  group_by(rep, error_dia_abco) %>% 
  summarize(test =min(error_dia_abco)-max(error_dia_abco)) 
all(test$test==0)
```

```{r}
length(unique(test$error_dia_abco)) >10
```

### Pipo
```{r}
test <- dfsimallreps %>% 
  group_by(rep, error_dia_pipo) %>% 
  summarize(test =min(error_dia_pipo)-max(error_dia_pipo)) 
all(test$test==0)
```

```{r}
length(unique(test$error_dia_pipo)) >10
```

## Growth
```{r}
test <- dfsimallreps %>% 
  group_by(rep, coef_gr_shrubarea, Species) %>% 
  #filter(Species =="PIPO") %>% 
  summarize(test =min(coef_gr_shrubarea)-max(coef_gr_shrubarea)) 
all(test$test==0)
length(unique(test$coef_gr_shrubarea)) >10
remove(test)
```

## Mortality
```{r}
test <- dfsimallreps %>% 
  group_by(rep, coef_gr_mort_abco) %>% 
  summarize(test =min(coef_gr_mort_abco)-max(coef_gr_mort_abco)) 
all(test$test==0)
length(unique(test$coef_gr_mort_abco))>10
```

```{r}
test <- dfsimallreps %>% 
  group_by(rep, coef_gr_mort_pipo) %>% 
  summarize(test =min(coef_gr_mort_pipo)-max(coef_gr_mort_pipo)) 
all(test$test==0)
length(unique(test$coef_gr_mort_pipo))>10
```

# Test climate years
```{r}
test <- dfsimallreps %>% 
  group_by(Years, rep, Species) %>% 
  mutate(sum_emerged = sum(emerged)) %>% 
  ungroup() %>% 
  dplyr::select(rep, Years, Year, Species, historic_year, sum_emerged) %>% 
  distinct() %>% 
  arrange(rep, Years)
test
```

```{r}
load("~/Shrubs-Seedlings/data/PRISM/clean_1970-present.Rdata")
df <- df %>% ungroup()
```

```{r}
join_test <- left_join(test, df, by = c("historic_year" = "water_year")) %>% 
  filter(Year != min_year) %>% 
  arrange(Years) 
join_test %>% 
  tail()
```


#### Plot the relationships between variables inputting the diameter growth equations to compare them to what I saw in the dendro analysis
```{r}
test <- dfsimallreps %>% 
  filter(Years %in% c(19,20)) %>% 
  dplyr::select(Sdlg, Species, Ht_cm1, dia.cm, Years, pred_exp, rep, ID_withinrep) %>% 
  tbl_df() %>% 
  arrange(Sdlg)
test <- test %>% 
  mutate(ID = paste(Sdlg, rep, ID_withinrep, sep = "-"))

test2 <- pivot_wider(test, names_from = "Years", values_from = "dia.cm", id_cols = c("rep", "ID"))

test2 <- test2 %>% 
  rename(dia.cmYear19 = `19`, dia.cmYear20 = `20`)

ggplot(test2)+
  geom_point(aes(x = dia.cmYear19, y = dia.cmYear20, col = as.factor(rep)))+
  geom_abline(aes(slope = 1, intercept = 0))+
  theme_minimal()+
  ylim(0,20)+
  xlim(0,20)
```
