---
title: "Clean and Compile 2016 Fire Footprint data"
author: "Carmen"
date: "September 20, 2017"
output: 
    html_document:
        toc: TRUE
        toc_depth: 1
---

```{r, include = F}
require(readxl)
require(dplyr)
require(tidyr)
```

# Load data
```{r}
load(file="~/Shrubs-Seedlings/compiled_data/shrub_master_data_2016.Rdata")
```

## Add years since fire
```{r}
df <- droplevels(df)
df <- df %>% 
  mutate(Years = ifelse(Fire == "AMCR", 8, 0)) %>% 
  mutate(Years = ifelse(Fire == "CLVD", 24, Years)) %>% 
  mutate(Years = ifelse(Fire == "FRDS", 12, Years)) %>% 
  mutate(Years = ifelse(Fire == "PLKN", 43, Years)) %>% 
  mutate(Years = ifelse(Fire == "STAR", 14, Years)) %>% 
  mutate(Years = ifelse(Fire == "WRTS", 35, Years))
summary(as.factor(df$Years))
```

# Add DIFN degrees from FV2200 output file
```{r}
setwd("~/../Dropbox (Stephens Lab)/SORTIE/Shrubs_Summer16/Completed_Data_and_Photos/LAI-2000_data/")
DIFNl53 <- read.table(file="AllDIFNGaps1-4",header=T,sep="\t")
names(df)
DIFNl53 <- distinct(DIFNl53)

DIFNl53$LAI_File <- as.factor(DIFNl53$LAI_File)
df <- left_join(df, DIFNl53, by=c("Light_File"="LAI_File")) %>%
  rename(DIFN.all = DIFN.x) %>%
  rename(DIFN.53 =DIFN.y) %>%
  select(-SMP, -TransComp, -Model, -Records, -ScattCorr)
```

## Find which seedlings have DIFN.all but lack DIFN.53
```{r}
fix <- subset(df, !is.na(df$DIFN.all) & is.na(df$DIFN.53))
fix
```

## Fill in a couple seedlings with funky DIFN situations

Seedlings 3 and 9 have two light files. I average them for 3 and use one for 9 because the other one is funky

```{r}
df[df$Sdlg==9,"DIFN.53"] <- DIFNl53[DIFNl53$LAI_File==15,"DIFN"]
df[df$Sdlg==3,"DIFN.53"] <- mean(DIFNl53[DIFNl53$LAI_File%in%c(17,19),"DIFN"])

fix <- subset(df, !is.na(df$DIFN.all) & is.na(df$DIFN.53))
```

## Save
```{r}
setwd("~/Shrubs-Seedlings/compiled_data/fire_footprints/")
save(df, file="master_data_2016.Rdata")
write.csv(df, file = "master_data_2016.csv", row.names = F)
```
