---
title: "Render all"
author: "Carmen"
date: "March 20, 2019"
output: 
  html_document:
    toc: TRUE
---

This code contains all of the steps necessary to clean and analyze Fire Footprint data

```{r prep}
library(knitr)
setwd("~/Shrubs-Seedlings/code/FireFootprints_analysis/")
```

# Cleaning
```{r cleaning, message = F, warning = F}
strt <- Sys.time()
rmarkdown::render("clean_seedlings_2016.Rmd", "html_document", quiet = T)
rmarkdown::render("clean_shrubs.Rmd", "html_document", quiet = T)
rmarkdown::render("clean_combine_2016-only.Rmd", "html_document", quiet = T)
rmarkdown::render("clean_combine_2016-2017.Rmd", "html_document", quiet = T)
rmarkdown::render("add_site_class.Rmd", "html_document", quiet = T)
rmarkdown::render("Heat_load.Rmd", "html_document", quiet = T)
rmarkdown::render("Clean_vert_growth.Rmd", "html_document", quiet = T)
print(strt-Sys.time())
```

# Main Analysis
```{r main_analysis, message = F, warning = F}
strt <- Sys.time()
#rmarkdown::render("DIFN_analysis.Rmd", "html_document", quiet= T)
rmarkdown::render("VSURF_pine.Rmd", "html_document", quiet = T)
rmarkdown::render("VSURF_fir.Rmd", "html_document", quiet = T)
rmarkdown::render("Pinus_vertical_growth.Rmd", "html_document", quiet = T)
rmarkdown::render("fir_vert_growth_all_years.Rmd", "html_document", quiet = T)
print(strt-Sys.time())
```

# Checks - these should all be TRUE
```{r check, message = F, warning = F}
source(purl("tests/checks.Rmd", quiet = T))
nrow(dups) == 0
nrow(mismatch) == 0
all(siteclass %in% c(2,3,4,6))
sum(check_years$check)==0
```

