---
title: "Compile and Clean Dendro Data"
author: "Carmen"
date: "December 11, 2018"
output: 
  html_document:
    toc: TRUE
---

```{r, include = F}
require(tidyverse)
require(dplR)
require(readxl)
```

# Read in and compile dendro files
```{r}
setwd("~/Shrubs-Seedlings/code/GrowthMortality_Analysis/")
if(Sys.info()[1]=="Darwin"){
  files <- list.files("../../../Dropbox (Stephens Lab)/SORTIE/Growth_mortality/data/Growth Mortality Dendro Data/",full.names = T, pattern = ".raw")
} else{
  files <- list.files("../../../../Dropbox (Stephens Lab)/SORTIE/Growth_mortality/data/Growth Mortality Dendro Data/", full.names = T, pattern = ".raw")
}
```

## Make a dendro rwl and a separate data frame, so that you can manipulate the data frame without it losing rwl status
```{r, message = F, warning = F}
df <- data.frame()
for(i in 1:length(files)){
  file <- files[i]
  rwli <- read.rwl(file)
  if(i >1){
    rwl <- combine.rwl(rwl, rwli)
  } else {
    rwl <- rwli
  }
  dfi <- as.data.frame(t(as.data.frame(rwli)))
  dfi$series <- paste(row.names(dfi))
  delim <- read.delim(file, header = F)
  delim$V1 <- as.character(delim$V1)
  board <- sapply(delim, substr, 74,79)
  board <- unique(board)
  print(board)
  dfi <- dfi %>% 
    mutate(board = board[1])
  if(i == 1){
    df <- dfi
    } else{
     df <- full_join(df, dfi) 
    }
}
```

## Rearrange
```{r}
df <- df %>% 
  dplyr::select(series, board, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`, everything())
df_bu <- df
```

# Save
```{r}
save(df, file = "../../compiled_data/dendro_joined.Rdata")
save(rwl, file = "../../compiled_data/rwl_joined.Rdata")
```

