---
title: "Vertical growth analysis"
author: "Carmen"
date: "November 18, 2017"
output: 
    html_document:
        toc: TRUE
---

```{r, include = F}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(effects)
```

# Load data
```{r}
setwd("~/Shrubs-Seedlings/code/GrowthMortality_Analysis/")
load(file = "../../compiled_data/growth_mortality/df_vert.Rdata")
```

#  Make dead a factor
```{r}
df <- df %>% 
  mutate(DEAD_ALIVE = as.factor(DEAD_ALIVE))
```

# Plot growth by year
```{r}
df2 <- gather(df, key = "year", value = "gr_rel", c(gr1, gr2, gr3)) %>% 
  mutate(year = ifelse(year == "gr1", "top growth", year)) %>% 
  mutate(year = ifelse(year == "gr2", "top growth - 1", year)) %>% 
  mutate(year = ifelse(year == "gr3", "top growth - 2", year)) %>% 
  mutate(year = as.factor(year))

df2$year <-  factor(df2$year, levels = rev(levels(df2$year)))

df2 %>% dplyr::select(year, gr_rel, SEEDLING)
ggplot(df2)+
  geom_boxplot(aes(x = year, y = log(gr_rel), fill = DEAD_ALIVE))+
  facet_wrap(~SPECIES)
```

# Summarize n by species
```{r}
df2 %>% 
  dplyr::select(SPECIES, DEAD_ALIVE, SEEDLING) %>% 
  distinct() %>%
  group_by(SPECIES, DEAD_ALIVE) %>% 
  summarize(n())
```


# Nice graphs for publication

## ABCO
```{r}
dfa <- df %>% 
  filter(SPECIES == "ABCO") %>% 
  group_by(DEAD_ALIVE) %>% 
  mutate(mean_log_gr = mean(log10_gr_rel_ave))
ggplot(dfa)+
  geom_boxplot(aes(x = DEAD_ALIVE, y = log10_gr_rel_ave, fill = DEAD), alpha = .5)+
  geom_point(aes(x = DEAD_ALIVE, y = mean_log_gr, col = DEAD), size = 2)+
  scale_fill_manual(values = c("#c7e9c0", "#fdd0a2"))+
  scale_color_manual(values = c("#31a354", "#e6550d"))+
  xlab("")+
  scale_x_discrete(labels = c("Alive", "Dead"))+
  ylab("Relative growth rate")+
  theme_bw()+
  scale_y_continuous(breaks = c(log10(0.01), log10(0.1), log10(1)), labels = c(0.01, 0.1, 1), limits = c(log10(0.007), log10(1.1)))+
  #ggtitle("ABCO average relative vertical growth,\nlog transformed")+
  theme(legend.position = "none", text=element_text(size=16))
  
  
  
ggsave(file = "../../results/figures/GrowthMortality/Fir_vert_boxplot.png", width = 4, height = 6, dpi = 400)
```


## PIPO
```{r}
dfp <- df %>% 
  filter(SPECIES == "PIPO") %>% 
  group_by(DEAD_ALIVE) %>% 
  mutate(mean_log_gr = mean(log10_gr_rel_ave))
ggplot(dfp)+
  geom_boxplot(aes(x = DEAD_ALIVE, y = log10_gr_rel_ave, fill = DEAD), alpha = .5)+
  geom_point(aes(x = DEAD_ALIVE, y = mean_log_gr, col = DEAD), size = 2)+
  scale_fill_manual(values = c("#c7e9c0", "#fdd0a2"))+
  scale_color_manual(values = c("#31a354", "#e6550d"))+
  xlab("")+
  scale_y_continuous(breaks = c(log10(0.01), log10(0.1), log10(1)), labels = c(0.01, 0.1, 1), limits = c(log10(0.007), log10(1.1)))+
  scale_x_discrete(labels = c("Alive", "Dead"))+
  ylab("Relative growth rate")+
  theme_bw()+
  #ggtitle("PIPO average relative vertical growth,\nlog transformed")+
  theme(legend.position = "none", text=element_text(size=16))
  
ggsave(file = "../../results/figures/GrowthMortality/Pine_vert_boxplot_ppt.png", width = 4, height = 6, dpi = 400)
```


# Make separate df for each species
```{r}
dfa <- df %>% filter(SPECIES == "ABCO")
dfp <- df %>% filter(SPECIES == "PIPO")
```

# GLM for abco

## Run the model
```{r}
GLM_abco <- glm(DEAD ~ log_gr_rel_ave, family = binomial(link = "logit"), data = dfa)
anova(GLM_abco, test = "Chi")
```

Strong significant difference.

# GLM for pipo


## Look at drop1
```{r}
GLM_pipo <- glm(DEAD ~ log_gr_rel_ave, family = binomial(link = "logit"), data = dfp)
summary(GLM_pipo)
anova(GLM_pipo, test = "Chi")
```

Strong significant difference
