---
title: "simulations"
author: "Carmen"
date: "May 16, 2019"
output: 
    html_document:
        toc: TRUE
---

```{r, include = F}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(effects)
require(MASS)
```

# Load data
```{r}
setwd("~/Shrubs-Seedlings/code/GrowthMortality_Analysis/")
load(file = "../../compiled_data/growth_mortality/df_vert.Rdata")
```

#  Make dead a factor
```{r}
df <- df %>% 
  mutate(DEAD_ALIVE = as.factor(DEAD_ALIVE))
```

# Make separate df for each species
```{r}
dfa <- df %>% filter(SPECIES == "ABCO")
dfp <- df %>% filter(SPECIES == "PIPO")
```

# SIMULATIONS

## Visually compare distributions
```{r}
means <- dfp %>% 
  group_by(DEAD_ALIVE) %>% 
  summarize(mean = mean(log_gr_rel_ave))
sd <- dfp %>% 
  group_by(DEAD_ALIVE) %>% 
  summarize(sd = sd(log_gr_rel_ave))
sd
```

```{r}
x <- seq(-4, 0, length=1000)
y <- dnorm(x, mean=means[[2,2]], sd=sd[[2,2]])
pdf_dead <- as.data.frame(cbind(x, y))
```

```{r}
x <- seq(-4, 0, length=1000)
y <- dnorm(x, mean=means[[1,2]], sd=sd[[1,2]])
pdf_live <- as.data.frame(cbind(x, y))
```

```{r}
ggplot()+
  geom_histogram(data = dfp %>% filter(DEAD_ALIVE=="DEAD"), aes(log_gr_rel_ave, stat(density)), bins = 20, alpha = .2, col = "red", fill = "red")+
  theme_bw()+
  geom_histogram(data = dfp %>% filter(DEAD_ALIVE=="ALIVE"), aes(log_gr_rel_ave, stat(density)), bins = 20, alpha = .2, col = "dark green", fill = "dark green")+
  geom_vline(data = means, aes(xintercept = mean, col = DEAD_ALIVE))+
  scale_color_manual(values = c("dark green", "red"))+
  geom_line(data = pdf_dead, aes(x = x, y = y), col = "red")+
  geom_line(data = pdf_live, aes(x = x, y = y), col = "dark green")
  
ggsave("../../results/figures/GrowthMortality/histogram_dead_alive_pipo.png")

```

# Actual simulations for PIPO

## Draw growth values randomly from each pipo data set 
```{r}
n_dead <- unlist(dfp %>% filter(DEAD_ALIVE=="DEAD") %>% summarize(n()))
gr_set_dead <- dfp %>% filter(DEAD_ALIVE=="DEAD") %>% dplyr::select(log_gr_rel_ave)
gr_set_dead <- gr_set_dead[[1]]
```

```{r}
n_dead <- unlist(dfp %>% filter(DEAD_ALIVE=="DEAD") %>% summarize(n()))
gr_set_dead <- dfp %>% filter(DEAD_ALIVE=="DEAD") %>% dplyr::select(log_gr_rel_ave)
gr_set_dead <- gr_set_dead[[1]]
```

```{r}
n_alive <- n_dead*(524/6)
gr_set_alive <- dfp %>% filter(DEAD_ALIVE=="ALIVE") %>% dplyr::select(log_gr_rel_ave)
gr_set_alive <- gr_set_alive[[1]]
```


## Loop it 
```{r}
coefficient_gr <- c()
coefficient_int <- c()
for(i in 1:1000){
  dead_sample <- sample(gr_set_dead, size = n_dead, replace = TRUE)
  alive_sample <- sample(gr_set_alive, size = n_alive, replace = TRUE)
  live_df <- data.frame(gr = c(alive_sample))
  live_df$dead <- 0
  dead_df <- data.frame(gr = c(dead_sample))
  dead_df$dead <- 1
  df <- bind_rows(dead_df, live_df)
    glm <- glm(dead ~ gr, family = binomial(link = "logit"), data = df)
  coefficient_gr <- c(coefficient_gr, glm$coefficient[2])
  coefficient_int <- c(coefficient_int, glm$coefficient[1])
}
mean_coef_gr <- mean(coefficient_gr)
mean_coef_int <- mean(coefficient_int)
```

## Plot the mean coefficient and CI

### Calculate probabilities
```{r}
log_gr_rel <- seq(min(dfp$log_gr_rel_ave), max(dfp$log_gr_rel_ave), length=1000)
dfplot <- as.data.frame(log_gr_rel)
dfplot$prob <- exp(mean_coef_int + mean_coef_gr*log_gr_rel)/(1+exp(mean_coef_int + mean_coef_gr*log_gr_rel))
```

### CI
```{r}
CI_low_int <- sort(coefficient_int)[25]
CI_high_int <- sort(coefficient_int)[975]
CI_low_gr <- sort(coefficient_gr)[25]
CI_high_gr <- sort(coefficient_gr)[975]
```

```{r}
log_gr_rel <- seq(min(dfp$log_gr_rel_ave), max(dfp$log_gr_rel_ave), length=1000)
head(log_gr_rel)
dfplot_lower <- as.data.frame(log_gr_rel)
dfplot_lower$prob <- exp(mean_coef_int + CI_low_gr*log_gr_rel)/(1+exp(mean_coef_int + CI_low_gr*log_gr_rel))
```

```{r}
log_gr_rel <- seq(min(dfp$log_gr_rel_ave), max(dfp$log_gr_rel_ave), length=1000)
head(log_gr_rel)
dfplot_upper <- as.data.frame(log_gr_rel)
dfplot_upper$prob <- exp(mean_coef_int + CI_high_gr*log_gr_rel)/(1+exp(mean_coef_int + CI_high_gr*log_gr_rel))
```

# Plot it
```{r}
ggplot()+
  geom_line(data = dfplot, aes(x = log_gr_rel, y = prob*100))+
  geom_line(data = dfplot_lower, aes(x = log_gr_rel, y = prob*100), linetype = "dashed")+
  geom_line(data = dfplot_upper, aes(x = log_gr_rel, y = prob*100), linetype = "dashed")+
  theme_bw()+
  ylab("% Probability of being found dead")+
  xlab("Annual relative growth (height_2 - height_1)/\nheight_1")
```

```{r}
ggplot()+
  geom_line(data = dfplot, aes(x = exp(log_gr_rel), y = prob*100))+
  geom_line(data = dfplot_lower, aes(x = exp(log_gr_rel), y = prob*100), linetype = "dashed")+
  geom_line(data = dfplot_upper, aes(x = exp(log_gr_rel), y = prob*100), linetype = "dashed")+
  theme_bw()+
  xlim(0.03, .3)+
  ylim(0, 20)+
  ylab("% Probability of being found dead")+
  xlab("Annual relative growth defined as\n(height_2 - height_1)/\nheight_1")+
  geom_vline(aes(xintercept = exp(-1.70428)), col = "red")+
  geom_text(aes(x= exp(-1.70428), label="\nminimum fire footprint shrub competition", y = 12), colour="red", angle=90) +
  geom_vline(aes(xintercept = exp(-2.5877)), col = "red")+
  geom_text(aes(x= exp(-2.5877), label="\nmaximum fire footprint shrub competition", y = 12), colour="red", angle=90) +
  geom_vline(aes(xintercept = exp(-1.955775)), col = "red")+
  geom_text(aes(x= exp(-1.955775), label="\nmedian fire footprint shrub competition", y = 12), colour="red", angle=90) +
  ggtitle("Pine mortality probability in relation to growth\nbased on simulation results, with 95% confidence intervals")
ggsave("../../results/figures/GrowthMortality/predict_mortality_pipo.png")
```

# Calculate the range of mortality probabilities captured by the fire footprint growth data
```{r}
prob_min <- exp(mean_coef_int + mean_coef_gr*(-1.70428)/(1+exp(mean_coef_int + mean_coef_gr*(-1.70428))))
prob_max <- exp(mean_coef_int + mean_coef_gr*(-2.5877)/(1+exp(mean_coef_int + mean_coef_gr*(-2.5877))))
prob_min
prob_max
prob_min-prob_max
(prob_max-prob_min)/prob_min
```

```{r}
prob_median <- exp(mean_coef_int + mean_coef_gr*(-1.955775)/(1+exp(mean_coef_int + mean_coef_gr*(-1.955775))))
prob_quart1 <- exp(mean_coef_int + mean_coef_gr*(-1.8115886)/(1+exp(mean_coef_int + mean_coef_gr*(-1.8115886))))
prob_quart3 <- exp(mean_coef_int + mean_coef_gr*(-2.10016998)/(1+exp(mean_coef_int + mean_coef_gr*(-2.10016998))))
prob_median
prob_quart1
prob_quart3
prob_median - prob_quart1
prob_quart3 - prob_median 
```

